
=== Part One: Collection of basic interview questions

____
Common basic interview questions about mybatis framework
____

==== Mybatis 中 #\{}和 $\{}的区别是什么

#\{}是预编译处理, Mybatis 在处理#\{}时，会将 sql
中的#\{}转成?占位符，使用预编译替换，就是把$\{}替换成变量的值；

使用#\{}可以有效的防止 SQL 注入，提高系统安全性。

==== Mybatis 有几种分页方式

[arabic]
. 数组分页
. sql 分页
. 拦截器分页
. RowBounds 分页

==== RowBounds 是一次性查询全部结果吗为什么

==== Mybatis 逻辑分页和物理分页的区别是什么

物理分页速度上并不一定快于逻辑分页，逻辑分页速度上也并不一定快于物理分页。

物理分页总是优于逻辑分页：没有必要将属于数据库端的压力加诸到应用端来，就算速度上存在优势,然而其它性能上的优点足以弥补这个缺点。

==== Mybatis 是否支持延迟加载延迟加载的原理是什么

Mybatis 仅支持 association 关联对象和 collection
关联集合对象的延迟加载，association 指的就是一对一，collection
指的就是一对多查询。在 Mybatis 配置文件中，可以配置是否启用延迟加载
lazyLoadingEnabled=true|false。

它的原理是，使用 CGLIB
创建目标对象的代理对象，当调用目标方法时，进入拦截器方法，比如调用
a.getB().getName()，拦截器 invoke()方法发现 a.getB()是 null
值，那么就会单独发送事先保存好的查询关联 B 对象的 sql，把 B
查询上来，然后调用 a.setB(b)，于是 a 的对象 b 属性就有值了，接着完成
a.getB().getName()方法的调用。这就是延迟加载的基本原理。

当然了，不光是 Mybatis，几乎所有的包括
Hibernate，支持延迟加载的原理都是一样的。

==== 说一下 Mybatis 的一级缓存和二级缓存

* 一级缓存: 基于 PerpetualCache 的 HashMap 本地缓存，其存储作用域为
Session，当 Session flush 或 close 之后，该 Session 中的所有 Cache
就将清空，默认打开一级缓存。
* 二级缓存与一级缓存其机制相同，默认也是采用 PerpetualCache，HashMap
存储，不同在于其存储作用域为 Mapper(Namespace)，并且可自定义存储源，如
Ehcache。默认不打开二级缓存，要开启二级缓存，使用二级缓存属性类需要实现
Serializable 序列化接口(可用来保存对象的状态),可在它的映射文件中配置 ；

____
对于缓存数据更新机制，当某一个作用域(一级缓存 Session/二级缓存
Namespaces)的进行了 C/U/D 操作后，默认该作用域下所有 select 中的缓存将被
clear。
____

==== Mybatis 和 Hibernate 的区别有哪些

[arabic]
. Mybatis 和 hibernate 不同，它不完全是一个 ORM 框架，因为 MyBatis
需要程序员自己编写 Sql 语句。
. Mybatis 直接编写原生态 sql，可以严格控制 sql
执行性能，灵活度高，非常适合对关系数据模型要求不高的软件开发，因为这类软件需求变化频繁，一但需求变化要求迅速输出成果。但是灵活的前提是
mybatis
无法做到数据库无关性，如果需要实现支持多种数据库的软件，则需要自定义多套
sql 映射文件，工作量大。
. Hibernate
对象/关系映射能力强，数据库无关性好，对于关系模型要求高的软件，如果用
hibernate 开发可以节省很多代码，提高效率。

==== Mybatis 有哪些执行器（Executor）

Mybatis 有三种基本的执行器（Executor）：

[arabic]
. SimpleExecutor：每执行一次 update 或 select，就开启一个 Statement
对象，用完立刻关闭 Statement 对象。
. ReuseExecutor：执行 update 或 select，以 sql 作为 key 查找 Statement
对象，存在就使用，不存在就创建，用完后，不关闭 Statement
对象，而是放置于 Map 内，供下一次使用。简言之，就是重复使用 Statement
对象。
. BatchExecutor：执行 update（没有 select，JDBC 批处理不支持
select），将所有 sql
都添加到批处理中（addBatch()），等待统一执行（executeBatch()），它缓存了多个
Statement 对象，每个 Statement 对象都是 addBatch()完毕后，等待逐一执行
executeBatch()批处理。与 JDBC 批处理相同。

==== Mybatis 分页插件的实现原理是什么

分页插件的基本原理是使用 Mybatis
提供的插件接口，实现自定义插件，在插件的拦截方法内拦截待执行的
sql，然后重写 sql，根据 dialect
方言，添加对应的物理分页语句和物理分页参数。

==== Mybatis 如何编写一个自定义插件

Mybatis 自定义插件针对 Mybatis 四大对象（Executor、StatementHandler
、ParameterHandler 、ResultSetHandler ）进行拦截，具体拦截方式为：

* Executor：拦截执行器的方法(log 记录)
* StatementHandler ：拦截 Sql 语法构建的处理
* ParameterHandler ：拦截参数的处理
* ResultSetHandler ：拦截结果集的处理
