server:
  port: 8081
  servlet:
    context-path: /web
springfox:
  swagger:
    enabled: true
spring:
  profiles:
    active: dev
  servlet:
    multipart.max-file-size: 512MB
    multipart.max-request-size: 256MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: mysql
    password: mysql

#mybatis.type-aliases-package: pers.lyks.spring.*.model
#mybatis.mapper-locations: classpath*:pers/lyks/spring/*/mapper/*Mapper.xml

logging.config: classpath:logback.xml