
=== 简介

HTTP 是无状态的，它的底层协议是由状态的 TCP，但是 HTTP
的一次完整协议动作，里面是使用有状态的 TCP
协议来完成的。而每次协议动作之间没有任何关系。

=== Request Method

`+HTTP1.0 定义了三种请求方法： GET, POST 和 HEAD 方法。+`

`+HTTP1.1 新增了五种请求方法：OPTIONS, PUT, DELETE, TRACE 和 CONNECT 方法。+`

[width="100%",cols="<4%,^4%,<92%",options="header",]
|===
|序号 |方法 |描述
|1 |GET |请求指定的页面信息，并返回实体主体。

|2 |HEAD |类似于 get
请求，只不过返回的响应中没有具体的内容，用于获取报头

|3 |POST
|向指定资源提交数据进行处理请求（例如提交表单或者上传文件）。数据被包含在请求体中。POST
请求可能会导致新的资源的建立和/或已有资源的修改。

|4 |PUT |从客户端向服务器传送的数据取代指定的文档的内容。

|5 |DELETE |请求服务器删除指定的页面。

|6 |CONNECT |HTTP/1.1 协议中预留给能够将连接改为管道方式的代理服务器。

|7 |OPTIONS |允许客户端查看服务器的性能。

|8 |TRACE |回显服务器收到的请求，主要用于测试或诊断。
|===

=== HTTP 状态码

[source,text]
----
1xx：指示信息——表示请求已经接受，继续处理
2xx：成功——表示请求已经被成功接收、理解、接受。
3xx：重定向——要完成请求必须进行更进一步的操作
4xx：客户端错误——请求有语法错误或请求无法实现
5xx：服务器端错误——服务器未能实现合法的请求。
常见状态代码、状态描述、说明：
200 OK //客户端请求成功
400 Bad Request //客户端请求有语法错误，不能被服务器所理解
401 Unauthorized //请求未经授权，这个状态代码必须和 WWW-Authenticate 报头域一起使用
403 Forbidden //服务器收到请求，但是拒绝提供服务
404 Not Found //请求资源不存在，eg：输入了错误的 URL
500 Internal Server Error //服务器发生不可预期的错误
503 Server Unavailable //服务器当前不能处理客户端的请求，一段时间后可能恢复正常
----

=== HTTP 缓存

=== 拓展

HTTP Request Method 有 15 种 | 序号 | 方法 | 描述 | | :— | :——-:
|————————————————————————————- | |9|PATCH|实体中包含一个表，表中说明与该
URI 所表示的原内容的区别。
|10|MOVE|请求服务器将指定的页面移至另一个网络地址。
|11|COPY|请求服务器将指定的页面拷贝至另一个网络地址。
|12|LINK|请求服务器建立链接关系。 |13|UNLINK|断开链接关系。
|14|WRAPPED|允许客户端发送经过封装的请求。
|15|Extension-mothed|在不改动协议的前提下，可增加另外的方法
